
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import BobTokenContractArtifactJson from '../target/bob_token_contract-BobToken.json' with { type: 'json' };
export const BobTokenContractArtifact = loadContractArtifact(BobTokenContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract BobToken;
 */
export class BobTokenContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, BobTokenContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): BobTokenContract {
    return Contract.at(address, BobTokenContract.artifact, wallet) as BobTokenContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<BobTokenContract>(PublicKeys.default(), wallet, BobTokenContractArtifact, (instance, wallet) => BobTokenContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<BobTokenContract>(publicKeys, wallet, BobTokenContractArtifact, (instance, wallet) => BobTokenContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof BobTokenContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<BobTokenContract['methods'][M]>
  ) {
    return new DeployMethod<BobTokenContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      BobTokenContractArtifact,
      (instance, wallet) => BobTokenContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return BobTokenContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(BobTokenContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'game_counter' | 'game_secret_hashes' | 'game_hashes' | 'owner' | 'public_balances' | 'private_balances'> {
      return {
        game_counter: {
      slot: new Fr(1n),
    },
game_secret_hashes: {
      slot: new Fr(2n),
    },
game_hashes: {
      slot: new Fr(3n),
    },
owner: {
      slot: new Fr(4n),
    },
public_balances: {
      slot: new Fr(5n),
    },
private_balances: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'game_counter' | 'game_secret_hashes' | 'game_hashes' | 'owner' | 'public_balances' | 'private_balances'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** __commit_to_user_secrets(game_state: struct, encrypt_secret: field, mask_secret: field, player_id: field) */
    __commit_to_user_secrets: ((game_state: { state: { game_ended: boolean, move_count: FieldLike, mpc_state: { round_number: (bigint | number), user_encrypt_secret_hashes: FieldLike[], user_mask_secret_hashes: FieldLike[], previous_output_states: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }[] } } }, encrypt_secret: FieldLike, mask_secret: FieldLike, player_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __consume_opponent_move_and_update_game_state(input_state: struct, user_state: struct, player_id: field) */
    __consume_opponent_move_and_update_game_state: ((input_state: { state: { game_ended: boolean, move_count: FieldLike, mpc_state: { round_number: (bigint | number), user_encrypt_secret_hashes: FieldLike[], user_mask_secret_hashes: FieldLike[], previous_output_states: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }[] } } }, user_state: { state: { encrypt_secret: FieldLike, mask_secret: FieldLike, visible_squares: FieldLike[], game_state: { id: FieldLike, player_id: FieldLike, has_moved: FieldLike }[] } }, player_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __create_move(x1: field, y1: field, x2: field, y2: field) */
    __create_move: ((x1: FieldLike, y1: FieldLike, x2: FieldLike, y2: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __empty_black_state() */
    __empty_black_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __empty_game_state() */
    __empty_game_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __empty_white_state() */
    __empty_white_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** args_hash_err(_user_state: struct) */
    args_hash_err: ((_user_state: { state: { encrypt_secret: FieldLike, mask_secret: FieldLike, visible_squares: FieldLike[], game_state: { id: FieldLike, player_id: FieldLike, has_moved: FieldLike }[] } }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_game_private(user_secret: field, user_mask: field, password: field) */
    create_game_private: ((user_secret: FieldLike, user_mask: FieldLike, password: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** join_game_private(game_id: integer, user_secret: field, user_mask: field, password: field) */
    join_game_private: ((game_id: (bigint | number), user_secret: FieldLike, user_mask: FieldLike, password: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** make_move_white_private(game_id: integer, game_state: struct, _user_state: struct, _move_data: struct) */
    make_move_white_private: ((game_id: (bigint | number), game_state: { state: { game_ended: boolean, move_count: FieldLike, mpc_state: { round_number: (bigint | number), user_encrypt_secret_hashes: FieldLike[], user_mask_secret_hashes: FieldLike[], previous_output_states: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }[] } } }, _user_state: { state: { encrypt_secret: FieldLike, mask_secret: FieldLike, visible_squares: FieldLike[], game_state: { id: FieldLike, player_id: FieldLike, has_moved: FieldLike }[] } }, _move_data: { state: { x1: FieldLike, y1: FieldLike, x2: FieldLike, y2: FieldLike } }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_private(employee: struct, amount: integer) */
    mint_private: ((employee: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_public(employee: struct, amount: integer) */
    mint_public: ((employee: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_balance_of(owner: struct) */
    private_balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_to_public(amount: integer) */
    private_to_public: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_balance_of(owner: struct) */
    public_balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_to_private(amount: integer) */
    public_to_private: ((amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** setup() */
    setup: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_private_state() */
    sync_private_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_ownership(new_owner: struct) */
    transfer_ownership: ((new_owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_private(to: struct, amount: integer) */
    transfer_private: ((to: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer_public(to: struct, amount: integer) */
    transfer_public: ((to: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** update_user_state_from_move(is_first_two_moves: boolean, _user_state: struct, _move_data: struct, player_id: field) */
    update_user_state_from_move: ((is_first_two_moves: boolean, _user_state: { state: { encrypt_secret: FieldLike, mask_secret: FieldLike, visible_squares: FieldLike[], game_state: { id: FieldLike, player_id: FieldLike, has_moved: FieldLike }[] } }, _move_data: { state: { x1: FieldLike, y1: FieldLike, x2: FieldLike, y2: FieldLike } }, player_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
}
